github:
  access_token: <%= Rails.application.credentials.dig(:github, :access_token) %>
  client_id: <%= Rails.application.credentials.github[:client_id] %>
  client_secret: <%= Rails.application.credentials.github[:client_secret] %>
  callback_url: "https://coreview.mochimochifarao.com/oauth/callback?provider=github"
mattermost:
  webhook_url: <%= Rails.application.credentials.dig(:mattermost, :webhook_url) %>
